### ISSUE TITLE
[Future] Rename the `src` folder to `icd_coding_benchmark` (or any other name we can think of for the library)

### ISSUE THREAD

**Issue by abheesht17** [dalgu90/icd-coding-benchmark#27]
Generally, in libraries, all the code is present in a folder with the same name as the library. All the setup and config files are present outside this directory (i.e., they are present in the root directory). Some library examples for the same are:

https://github.com/facebookresearch/mmf/tree/main/mmf/models
https://github.com/huggingface/transformers

I don't want the pace of contribution of models to be disturbed...so, let's keep it `src` for now, and change it once we are done adding a reasonable number of models.

**Comment by dalgu90** [comment]
Resolved in #47
